"""empty message

Revision ID: 3faee846eb38
Revises: 2032dc756d7b
Create Date: 2023-07-09 13:50:13.988024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3faee846eb38'
down_revision = '2032dc756d7b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_number',
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('number_id', sa.INTEGER(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['number_id'], ['number.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_number')
    op.drop_table('user')
    # ### end Alembic commands ###
